export const CLASS_LEVELS = [
    "SD Kelas 1",
    "SD Kelas 2",
    "SD Kelas 3",
    "SD Kelas 4",
    "SD Kelas 5",
    "SD Kelas 6",
    "SMP Kelas 7",
    "SMP Kelas 8",
    "SMP Kelas 9",
    "SMA Kelas 10",
    "SMA Kelas 11",
    "SMA Kelas 12"
];

export const SUBJECTS_BY_LEVEL = {
  "SD": [
    "Matematika",
    "IPA (Sains)",
    "IPS (Sejarah, Geografi)",
    "Bahasa Indonesia",
    "Bahasa Inggris",
    "Pendidikan Pancasila (PPKn)",
    "Lainnya",
  ],
  "SMP": [
    "Matematika",
    "IPA Terpadu (Fisika, Biologi)",
    "IPS Terpadu (Sejarah, Geografi, Ekonomi)",
    "Bahasa Indonesia",
    "Bahasa Inggris",
    "Pendidikan Pancasila (PPKn)",
    "Informatika",
    "Seni Budaya",
    "Lainnya",
  ],
  "SMA": [
    "Matematika (Wajib)",
    "Matematika (Peminatan)",
    "Fisika",
    "Kimia",
    "Biologi",
    "Geografi",
    "Sejarah",
    "Sosiologi",
    "Ekonomi",
    "Bahasa Indonesia",
    "Bahasa Inggris",
    "Informatika",
    "Lainnya",
  ],
};
